name: Build and Publish to Modrinth

on:
  push:
    tags:
      - '*'  # cualquier tag dispara el workflow
  release:
    types: [ created ]  # se dispara al crear una release en GitHub
  workflow_dispatch:  # también puedes ejecutarlo manualmente

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Set tag variable for push
        if: ${{ github.event_name == 'push' }}
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set tag variable for release
        if: ${{ github.event_name == 'release' }}
        run: echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Publish to Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_VERSION: ${{ env.TAG }}   # pasa el tag como versión
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
